name: Deploy Jupyter Book

on:
  push:
    branches:
      - main # Or the branch you want to trigger deployments from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.11 # Replace with your desired Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry add jupyter-book
      - name: Build Jupyter Book
        run: |
          poetry run jupyter-book toc from-project .
          poetry run jupyter-book build .
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html # Or ./_build/latex if you are building a latex book